name: pr-libbpfgo
on: 
  pull_request:
    paths: 
      - "libbpfgo/**"
jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-20.04]
    defaults:
      run:
        working-directory: libbpfgo
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: unit test helpers
        run: go test ./helpers
      - name: selftest
        run: |
          sudo ./selftest/run.sh
      - name: compile against tracee
        run: |
          ./testing/compile-tracee.sh
