name: PR
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          go-version: 1.18
      - name: Test Helpers
        run: go test ./helpers
  self-tests:
    name: Selftests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          go-version: 1.18
      - name: Static Selftests
        run: |
          sudo make selftest-static-run
  compile-trace:
    name: Compile Tracee
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          go-version: 1.18
      - name: Compile Tracee
        run: |
          sudo ./testing/compile-tracee.sh
