name: pr
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  unit-tests:
    name: unit test helpers
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          go-version: 1.18
      - name: unit test helpers
        run: go test ./helpers

  self-test:
    name: selftest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          go-version: 1.18
      - name: selftest
        run: |
          sudo make selftest-static-run

  compile-trace:
    name: compile against tracee
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          go-version: 1.18
      - name: compile against tracee
        run: |
          sudo ./testing/compile-tracee.sh
