name: pr
on: 
  workflow_dispatch: {}
  pull_request:
    branches: 
      - main
jobs:
  build-test:
    name: Run Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: unit test helpers
        run: go test ./helpers
      - name: selftest
        run: |
          sudo make selftest-static-run
      - name: compile against tracee
        working-directory: ./libbpfgo
        run: |
          sudo ./testing/compile-tracee.sh
